### ISSUE TITLE
Restrict the authorization scope needed by the Release integration

### ISSUE THREAD

**Issue by Qix-** [zeit/release#107]
Right now, we have "Full control of private repositories", which is incredibly broad. Is there any chance for us to reduce the auth scopes that we use?

<img width="613" alt="screen shot 2017-10-12 at 5 32 23 pm" src="https://user-images.githubusercontent.com/885648/31525211-719d4162-af73-11e7-96d1-25393a415814.png">

**Comment by leo** [comment]
Sadly not. The GitHub Auth API requires you to to set the access by scope and the list of scopes they provide [isn't that long](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/).

We need at least `repo` (which is the only one we're using) in order to write/modify/read releases for public AND private repositories.

The token is eventually only saved forever on the user's device. And at this place, I assume there are plain-text tokens laying around (with full access even) for Git either way.
