### ISSUE TITLE
Make bump from canary to master get all commits from latest master release

### ISSUE THREAD

**Issue by timneutkens** [zeit/release#127]
So what I run into with Next.js when merging canary into master is that `release` will only get the commits from the `latest canary` to the new `master release`.

For example:

1. I release Next.js 6.0.0
2. We started development on Next.js 6.0.1 with a canary release: `6.0.1-canary.0`
3. We did some more commits
4. Releasing them as `6.0.0-canary.1`. Commits from `6.0.1-canary.0` to  `6.0.1-canary.1` are caught by release and added to the release notes
5. I finished the canary branch and it's ready to be released
6. I run `release patch` on the master branch with all commits from the canary branch
7. Release doesn't detect all commits from `6.0.0` to `6.0.1`, making me have to manually copy-paste all release notes from canary releases.

@leo can we add support for this behaviour? It'd be a huge time saver for me when releasing 😌

**Comment by chabou** [comment]
Same problem with `hyper`.
And problem is even bigger when `master` and `canary` has diverged (using a cherry-pick strategy to merge `canary` into `master`). When you are releasing a first canary release after a stable release, it can't find last tag in canary branch and it seems to consider all commits from divergence.

This is due to this PR: https://github.com/zeit/release/pull/71
This is explicitly said that all branches are now valid to find previous tag which is good for hotfix/maintenance branch strategy. But not in our case.

Several simple ways to fix this:
* add an option to specify the previous tag manually. It will help to resolve all edge cases.
* add an option to strictly choose the previous tag of current branch.

More complicated solution that can come after:
* detect when previous tag is not on same branch, get previous tag on same branch and let user decide interactively which origin tag to choose: <previous_tag>, <previous_tag_on_same_branch> or specify manually.
