### ISSUE TITLE
Use most recent local tag as GitHub releases tag

### ISSUE THREAD

**Issue by leo** [zeit/release#37]

**Comment by aesopwolf** [comment]
Not sure if this is in the same vein or not, but it would be great to skip running these commands altogether:

```
git tag <version-number>
git push --tags
```

Given the GitHub UI will create a new tag for you automatically then I think it should be possible to skip the error message `Error! Release already exists. Opening in browser...` altogether.

![image](https://cloud.githubusercontent.com/assets/6847633/21747626/bb458a5e-d521-11e6-836a-08a8c73cb983.png)

To take it one step further, we could probably automatically generate the version number and pass it to the GitHub UI, since we already know if the changes are minor or patch. (not sure how to determine major changes though).

**Comment by leo** [comment]
Closed in favor of https://github.com/zeit/release/issues/41
