### ISSUE TITLE
New mechanism

### ISSUE THREAD

**Issue by leo** [zeit/release#41]
- We shouldn't expect a git tag to exist
- Based on whether or not the user selected any major changes, minor changes or patches, the package should create a new tag by itself (incremented from the last tag)

**Comment by aesopwolf** [comment]
Should this also perform `git push --tags` under the hood? Perhaps right before opening the browser window?

**Comment by dinoboff** [comment]
So the process  would be something like that?
```
# first manual release
npm version patch
git push origin master v0.0.1

# disable tagging and commiting version bump 
echo 'git-tag-version=false' >> .npmrc
git add .npmrc && git commit -m "add npm project settings"

# following releases
npm version patch
git add package.json && commit -m "bump version"
git push origin master
release
```
(the git command would be set a postversion run-script command)

**Comment by leo** [comment]
@aesopwolf [No.](https://github.com/zeit/release/issues/43)

**Comment by aesopwolf** [comment]
Ah, I guess not. I just saw your other issue https://github.com/zeit/release/issues/43 

This wouldn't create a tag within git itself, merely a tag to pass to the github release.

Is that correct?

**Comment by dinoboff** [comment]
@aesopwolf no, I think github would create the tag when you publish the draft release. Then you pull the tags

**Comment by leo** [comment]
@dinoboff Correct.

**Comment by dinoboff** [comment]
@leo 

When creating the release draft, `release` should probably set the ["target_commitish"](https://developer.github.com/v3/repos/releases/#create-a-release) field so that the tag github creates reference to commit the local HEAD commit and not the one the remote master references when the draft is published.

**Comment by leo** [comment]
@dinoboff Done!

**Comment by dinoboff** [comment]
@leo

Currently, `release` assume the tag exists and is pushed. "target_commitish" should be set to the tag hash itself.

Once `release` doesn't assume the tag exists, it will need to set "target_commitish" to either the tag hash or the HEAD hash when there's no tag.

**Comment by dinoboff** [comment]
Should it be closed?

If we can't rely an tag (or package.json), the user could provide an argument, request `release` to bump using same semantic than `npm version`, or according to the type of changes:

```shell
release [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-log]
```

**Comment by leo** [comment]
Let's keep the functionality like it is. I thought about this for a bit and i think it's better if we don't automate even more from here. Because of we do, we take a lot of flexibility away. We should keep letting people decide to modify their project and prepare it for the release. Once it's ready, the package can drop in and create the GitHub Release!

**Comment by aesopwolf** [comment]
I find myself manually going over a list of commits since last release to explicitly set the git tag before I can run `release`, and then I have to go through the same process again of looking at each commit since the last release through the interactive CLI.

I, personally, would love to see this feature actually implemented. Maybe it could be opt-in?

**Comment by leo** [comment]
What? The tag should always be set to the latest commit (the release commit).

**Comment by aesopwolf** [comment]
Correct, I run `git tag -a 1.x.x -m "1.x.x"` on the latest commit, but before I can run it I have to figure out what I'm actually going to tag it with. I do that by looking at a list of commits since the last release and thinking to myself "Does this commit bump the major, minor, or patch?".

After I run `git tag` I run `release` which takes me through the interactive CLI and then I feel like I'm doing the same work twice (categorizing commits).

Maybe I'm not following best practices?

**Comment by leo** [comment]
Well, you can [predefine](https://github.com/zeit/release/wiki/Change-Types#pre-defining-the-type-of-a-commit) them... 😊
