### ISSUE TITLE
Detect and ignore tag commits?

### ISSUE THREAD

**Issue by rauchg** [zeit/release#73]

**Comment by dinoboff** [comment]
Like e8556281f24746aee5b957881cdb168ac4aec27e ?

It should already skip it with https://github.com/zeit/release/blob/1.1.7/bin/release.js#L181

**Comment by dinoboff** [comment]
If you need to ignore the commit the tag annotate regardless of the subject being a semantic version, the commit range could be set to something like `["v1.2.3^@", "^v1.2.2"]` instead of `v1.2.2..v1.2.3`:

    <rev>^@, e.g. HEAD^@
    A suffix ^ followed by an at sign is the same as listing all parents of <rev>
    (meaning, include anything reachable from its parents, but not the commit itself).

Require alessioalex/git-commits#2 to be fixed.

However, If it's safe to ignore commit generated by npm, a tag might annotate a actual fix or feat. A cli option to enable/disable this behaviour would be welcome.

**Comment by dinoboff** [comment]
git-commit@1.3.0 supports revision range array:

```
const rev = [`${release.hash}^@`, `^${parent.hash}`];

gitCommits(repoPath, {rev});
```
